AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  transactions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ""
      MemorySize: 256
      Timeout: 10
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          YNAB_ACCESS_TOKEN: FM-2LTzdeJ4j61uMYT3swjzM-Yf3HS0Kj9gLWs95kuc
          OPENAI_API_KEY: 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
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::nathanfredericks-transactions/*
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:ca-central-1:187489282488:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:ca-central-1:187489282488:log-group:/aws/lambda/transactions:*
      SnapStart:
        ApplyOn: None
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: transactions
