AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  transactions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ""
      MemorySize: 256
      Timeout: 10
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::nathanfredericks-transactions/*
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:ca-central-1:187489282488:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:ca-central-1:187489282488:log-group:/aws/lambda/transactions:*
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:ca-central-1:187489282488:secret:prod/transactions-hK2wf2
      SnapStart:
        ApplyOn: None
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: transactions
