AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  transactions:
    Type: AWS::Serverless::Function

    Properties:
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Handler: index.handler
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          S3_BUCKET_NAME: nathanfredericks-transactions
          DYNAMODB_TABLE_NAME: TransactionOverrides
          YNAB_BUDGET_ID: e0e7f122-6f2f-41f3-9b84-6d8f49fd5eab
          YNAB_TANGERINE_ACCOUNT_ID: b8df1b5f-4163-43ce-9bd0-01cb1f824cf7
          YNAB_BMO_ACCOUNT_ID: 7920fe4c-4deb-4b33-a860-3b2b0d80085f
          SECRET_NAME: transactions
      EventInvokeConfig:
        MaximumRetryAttempts: 2
      Policies:
        - Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::nathanfredericks-transactions/*
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:ca-central-1:187489282488:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:ca-central-1:187489282488:log-group:/aws/lambda/transactions:*
            - Effect: Allow
              Action:
                - dynamodb:Scan
              Resource:
                - arn:aws:dynamodb:ca-central-1:187489282488:table/TransactionOverrides/index/*
                - arn:aws:dynamodb:ca-central-1:187489282488:table/TransactionOverrides
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: arn:aws:secretsmanager:ca-central-1:187489282488:secret:transactions-ZuMkXL
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: transactions
